### ISSUE TITLE
Usage with parallel test runs

### ISSUE THREAD

**Issue by parky128** [LironEr/cypress-mochawesome-reporter#44] opened 2021-07-15 12:52 UTC
Hi, not sure if this is the correct place to ask this but are there any limitations\caveats with using this reporter when running tests in Cypress in parallel mode?

Can this reporter be made aware of report files across multiple nodes and know how to combine these?

**Comment by LironEr** [comment] 2021-07-23 08:39
I never tried to use this reporter in parallel mode, but I don't think it would work.
Somehow the reporter needs to fetch the result files from each node and combine them, which is currently not implemented.

**Comment by LironEr** [comment] 2023-08-04 07:09
@lems3 can you please provide a simple repo with what you achieved so far? 
I may have a solution, but I would like to use an example so I would have something to work on

**Comment by LironEr** [comment] 2023-08-05 14:37
The repo and the steps helped me a LOT, thanks.

Please download this reporter `3.6.0-rc.0` version and then follow the steps [here](https://github.com/LironEr/cypress-mochawesome-reporter/tree/feat/support-parallel/examples/cypress-parallel)

Let me know if it worked for you and if you have any comments/suggestions about the solution.

If everything is okay, I will write more documentation and publish this version.

**Comment by sidsalunke** [comment] 2023-08-23 02:45
@LironEr I just tested out your version and it does work as expected. I was able to get a single report when running tests in parallel. Thanks!
I also noticed that when running your version, I get this error `Some test suites likely terminated without passing on results, exit with error`
![image](https://github.com/LironEr/cypress-mochawesome-reporter/assets/30222114/086bc308-a856-41bd-99b5-94083fceaff8)
Upon investigation, I can confirm that this happens due to the `excludeSpecPattern` in the cypress config. We do have 6 tests that have been excluded. It might be better to not worry about the tests that have been excluded to avoid this error/warning?

**Comment by LironEr** [comment] 2023-09-01 08:24
Hey @sidsalunke, I am glad to hear this version is working as expected (:
I will release `v3.6.0` soon, probably without changes.

As for the issue you noticed, I'm not sure if it's a cypress, cypress-parallel, or this reporter problem.
if you want you can create a repo with the problem and steps to reproduce the issue so I try to have a look.

**Comment by LironEr** [comment] 2023-09-09 09:59
Released in [v3.6.0](https://github.com/LironEr/cypress-mochawesome-reporter/releases/tag/v3.6.0) 🥳

**Closed by LironEr** 2023-09-09 09:59 UTC
Labels: enhancement
